### PR TITLE
Change userID to be int64 across all platforms

### LINKED ISSUE #43: Installation on raspberry pi 32 bit failed
Followed the steps in the README.md

```bash
go build -o timew-server
go: downloading github.com/mattn/go-sqlite3 v1.14.16
go: downloading github.com/lestrrat-go/jwx v1.2.25
go: downloading github.com/lestrrat-go/backoff/v2 v2.0.8
go: downloading golang.org/x/crypto v0.0.0-20220427172511-eb4f295cb31f
go: downloading github.com/lestrrat-go/httpcc v1.0.1
go: downloading github.com/lestrrat-go/iter v1.0.1
go: downloading github.com/lestrrat-go/blackmagic v1.0.0
go: downloading github.com/lestrrat-go/option v1.0.0
go: downloading github.com/pkg/errors v0.9.1
# github.com/timewarrior-synchronize/timew-sync-server/sync
sync/user_management.go:59:16: constant 9223372036854775807 overflows int
```

The build fails with an oveflowing int

System: Raspian Lite 32 Bit

### PR DESCRIPTION
**Pull request by joachimschmidt557**
Fixes #43

### CODE REVIEW

File: sync/user_management.go [hunk 1]
```diff
@@ -54,9 +54,9 @@ func GetUsedUserIDs() map[int]bool {
 }
 
 // GetFreeUserID returns the smallest valid unused user id
-func GetFreeUserID() int {
+func GetFreeUserID() int64 {
 	used := GetUsedUserIDs()
-	for i := 0; i <= math.MaxInt64; i++ {
+	for i := int64(0); i <= math.MaxInt64; i++ {
```
Comment (vstollen) [inline sync/user_management.go:59]: nit: we could also use `math.MaxInt`, to prevent using `int64` on 32 systems.

**Review by vstollen — DISMISSED** [review]

File: sync/user_management.go (hunk 1 above)
Comment (joachimschmidt557) [reply sync/user_management.go:59]: I think it is better to make `userID` a consistent type across all systems so that data can be migrated from system to system with different `int` sizes. This way, data from a 64-bit system with user IDs larger than 32 bits can be reused in a 32-bit system.

Comment (vstollen) [reply sync/user_management.go:59]: Fine for me. Storage seems to use `int` user ids as well:
https://github.com/timewarrior-synchronize/timew-sync-server/blob/ca5623596cf3eaaca7d629e822971f8c08d5cfd9/storage/storage.go#L29

**Review by vstollen — APPROVED** [review]
